"""Public interface for the official Xray-core provider.

Protocol-specific builders are split into sibling modules as their formal
dataset cases are implemented. Imports remain stable for the controller.
"""

from proxy_traffic_lab.providers.xray.runtime import (
    IMAGE_DIGEST_PATTERN,
    XRAY_CLIENT_CONTAINER,
    XRAY_OFFICIAL_IMAGE_TAG,
    XRAY_SERVER_CONTAINER,
    VlessTlsMaterial,
    client_logs,
    client_status,
    create_vless_tls_material,
    load_image_lock,
    load_vless_tls_material,
    lock_official_image,
    render_vless_tls_client,
    render_vless_tls_server,
    render_vmess_websocket_tls_client,
    render_vmess_websocket_tls_server,
    render_vmess_xhttp_h2_tls_client,
    render_vmess_xhttp_h2_tls_server,
    render_xray_case_client,
    render_xray_case_server,
    server_logs,
    server_status,
    start_client_container,
    start_server_container,
    stop_client_container,
    stop_server_container,
    validate_generated_client_address,
    validate_official_image_digest,
    validate_server_config_with_container,
    write_private_json,
)

__all__ = [
    "IMAGE_DIGEST_PATTERN",
    "XRAY_CLIENT_CONTAINER",
    "XRAY_OFFICIAL_IMAGE_TAG",
    "XRAY_SERVER_CONTAINER",
    "VlessTlsMaterial",
    "client_logs",
    "client_status",
    "create_vless_tls_material",
    "load_image_lock",
    "load_vless_tls_material",
    "lock_official_image",
    "render_vless_tls_client",
    "render_vless_tls_server",
    "render_vmess_websocket_tls_client",
    "render_vmess_websocket_tls_server",
    "render_vmess_xhttp_h2_tls_client",
    "render_vmess_xhttp_h2_tls_server",
    "render_xray_case_client",
    "render_xray_case_server",
    "server_logs",
    "server_status",
    "start_client_container",
    "start_server_container",
    "stop_client_container",
    "stop_server_container",
    "validate_generated_client_address",
    "validate_official_image_digest",
    "validate_server_config_with_container",
    "write_private_json",
]
